-- Oppretter tabeller i databasen 
CREATE TABLE IF NOT EXISTS Banestrekning(
Navn VARCHAR(40) PRIMARY KEY,
Fremdriftsenergi VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS Jernbanestasjon(
Navn VARCHAR(40) PRIMARY KEY,
HøydeOverHavet INTEGER
);

CREATE TABLE IF NOT EXISTS stasjonType(
JernbanestasjonNavn VARCHAR(40) NOT NULL,
BanestrekningNavn VARCHAR(40) NOT NULL,
Type VARCHAR(40),
PRIMARY KEY(JernbanestasjonNavn, BanestrekningNavn)
FOREIGN KEY(JernbanestasjonNavn) REFERENCES Jernbanestasjon(Navn)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(BanestrekningNavn) REFERENCES Banestrekning(Navn)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Vognoppsett(
ID INTEGER,
PRIMARY KEY(ID AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS Operatør(
Navn VARCHAR(40) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS Togrute(
TogruteID INTEGER,
KjørerHovedretning INTEGER,
OperatørNavn VARCHAR(40) NOT NULL,
VognoppsettID INTEGER NOT NULL,
PRIMARY KEY(TogruteID AUTOINCREMENT),
FOREIGN KEY(OperatørNavn) REFERENCES Operatør(Navn)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(VognoppsettID) REFERENCES Vognoppsett(ID)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS togruteStasjon(
JernbanestasjonNavn VARCHAR(40) NOT NULL,
TogruteID INTEGER NOT NULL,
Tid VARCHAR(40),
NummerInnom INTEGER,
PRIMARY KEY(JernbanestasjonNavn, TogruteID),
FOREIGN KEY(JernbanestasjonNavn) REFERENCES Jernbanestasjon(Navn)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(TogruteID) REFERENCES Togrute(TogruteID)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS UkedagTabell(
TogruteID INTEGER NOT NULL,
DagsNavn VARCHAR(40),
PRIMARY KEY(TogruteID, DagsNavn),
FOREIGN KEY(TogruteID) REFERENCES Togrute(TogruteID)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Kunderegister(
Kundenummer INTEGER PRIMARY KEY AUTOINCREMENT,
Navn VARCHAR(40), 
Epost VARCHAR(40) UNIQUE,
Mobilnummer INTEGER UNIQUE
);

CREATE TABLE IF NOT EXISTS Kundeordre(
Ordrenummer INTEGER PRIMARY KEY AUTOINCREMENT,
Dag VARCHAR(40),
Tid VARCHAR(40),
Kundenummer INTEGER NOT NULL,
FOREIGN KEY(Kundenummer) REFERENCES Kunderegister(Kundenummer)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Vogntype(
VognID INTEGER,
Navn VARCHAR(40),
OperatørNavn VARCHAR(40) NOT NULL,
PRIMARY KEY(VognID AUTOINCREMENT),
FOREIGN KEY(OperatørNavn) REFERENCES Operatør(Navn)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Sittevogn(
VognID INTEGER NOT NULL,
AntallRader INTEGER,
SeterPerRad INTEGER,
PRIMARY KEY(VognID),
FOREIGN KEY(VognID) REFERENCES Vogntype(VognID)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Sovevogn(
VognID INTEGER NOT NULL,
AntallKupeer INTEGER,
PRIMARY KEY(VognID),
FOREIGN KEY(VognID) REFERENCES Vogntype(VognID)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS tilgjengeligVogn(
VognID INTEGER NOT NULL,
VognoppsettID INTEGER NOT NULL,
vognNummer INTEGER,
PRIMARY KEY(VognID, VognoppsettID, vognNummer),
FOREIGN KEY(VognID) REFERENCES Vogntype(VognID)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(VognoppsettID) REFERENCES Vognoppsett(ID)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Delstrekning(
startStasjon VARCHAR(40) NOT NULL,
sluttStasjon VARCHAR(40) NOT NULL,
LengdeKM INTEGER, 
HarDobbeltspor INTEGER,
PRIMARY KEY(startStasjon, sluttStasjon, LengdeKM),
FOREIGN KEY(startStasjon) REFERENCES Jernbanestasjon(Navn)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(sluttStasjon) REFERENCES Jernbanestasjon(Navn)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Togruteforekomst(
TogruteID INTEGER NOT NULL,
Dato VARCHAR(40),
PRIMARY KEY(TogruteID, Dato),
FOREIGN KEY(TogruteID) REFERENCES Togrute(TogruteID)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Sete(
SeteNummer INTEGER,
VognID INTEGER NOT NULL,
PRIMARY KEY(SeteNummer, VognID),
FOREIGN KEY(VognID) REFERENCES Sittevogn(VognID)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Sovekupe(
KupeNummer INTEGER,
VognID INTEGER NOT NULL,
PRIMARY KEY(KupeNummer, VognID),
FOREIGN KEY(VognID) REFERENCES Sovevogn(VognID)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS seteBillett(
SeteNummer INTEGER NOT NULL,
vognNummer INTEGER NOT NULL,
VognID INTEGER NOT NULL,
Dato VARCHAR(40) NOT NULL,
TogruteID INTEGER NOT NULL,
Ordrenummer INTEGER NOT NULL,
Startindeks INTEGER NOT NULL,
Sluttindeks INTEGER NOT NULL,
PRIMARY KEY(SeteNummer, vognNummer, VognID, Dato, TogruteID, Ordrenummer),
FOREIGN KEY(SeteNummer, VognID) REFERENCES Sete(SeteNummer, VognID)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(TogruteID, Dato) REFERENCES Togruteforekomst(TogruteID, Dato)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(Ordrenummer) REFERENCES Kundeordre(Ordrenummer)
ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS kupeBillett(
KupeNummer INTEGER NOT NULL,
vognNummer INTEGER NOT NULL,
VognID INTEGER NOT NULL,
Dato VARCHAR(40) NOT NULL,
TogruteID INTEGER NOT NULL,
Ordrenummer INTEGER NOT NULL,
AntallSenger INTEGER NOT NULL,
Startindeks INTEGER NOT NULL,
Sluttindeks INTEGER NOT NULL,
PRIMARY KEY(KupeNummer, vognNummer, VognID, Dato, TogruteID, Ordrenummer),
FOREIGN KEY(KupeNummer, VognID) REFERENCES Sovekupe(KupeNummer, VognID)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(TogruteID, Dato) REFERENCES Togruteforekomst(TogruteID, Dato)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(Ordrenummer) REFERENCES Kundeordre(Ordrenummer)
ON DELETE CASCADE ON UPDATE CASCADE
);
